export const REQUEST_RESULTS = 'REQUEST_RESULTS';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const REQUEST_ASSET = 'REQUEST_ASSET';
export const RECEIVE_ASSET = 'RECEIVE_ASSET';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const QUERY_CHANGED = 'QUERY_CHANGED';
